document.addEventListener('DOMContentLoaded',()=>{
 const DD=window.PROVINCE_DATA;if(!DD)return;
 const indSel=document.querySelector('#mapIndicator'),yearSel=document.querySelector('#mapYear'),wrap=document.querySelector('#provinceMap'),tip=document.querySelector('#provinceMapTip'),geometrySource=document.querySelector('#geometrySource'),downloads=document.querySelector('#mapDownloads');
 const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().replace(/[-–—]/g,' ').replace(/\s+/g,' ').trim();
 const fmt=(ind,v)=>{if(v==null||!isFinite(+v))return '—';const n=+v,d=ind.decimals??1;if(ind.unit==='%')return n.toLocaleString('es-PE',{minimumFractionDigits:d,maximumFractionDigits:d})+'%';if(ind.unit==='S/')return 'S/ '+n.toLocaleString('es-PE',{maximumFractionDigits:d});if(ind.unit==='personas'||ind.unit==='casos')return n.toLocaleString('es-PE',{maximumFractionDigits:0});return n.toLocaleString('es-PE',{maximumFractionDigits:d})+(ind.unit?' '+ind.unit:'')};
 indSel.innerHTML=DD.indicators.map(i=>`<option value="${i.id}">${i.label}</option>`).join('');indSel.value=DD.defaultIndicator;
 let geo=null,geoLabel='';const current=()=>DD.indicators.find(i=>i.id===indSel.value);
 function fillYears(){const i=current();yearSel.innerHTML=i.years.slice().reverse().map(y=>`<option value="${y}">${y}</option>`).join('');yearSel.value=i.years.includes(DD.defaultYear)?String(DD.defaultYear):String(i.years[i.years.length-1])}
 function ringsOf(g){if(!g)return[];if(g.type==='Polygon')return g.coordinates;if(g.type==='MultiPolygon')return g.coordinates.flat();return[]}
 function geometryPoints(g){return ringsOf(g).flat()}
 function pathFor(g,project){const parts=[];ringsOf(g).forEach(r=>{if(!r.length)return;parts.push('M'+r.map((p,i)=>{const [x,y]=project(p);return `${i?'L':''}${x.toFixed(2)},${y.toFixed(2)}`}).join('')+'Z')});return parts.join('')}
 function colorScale(v,min,max){if(v==null||!isFinite(v))return '#EDF7FB';if(max<=min)return '#70CBEA';const t=Math.max(0,Math.min(1,(v-min)/(max-min)));const a=[218,244,252],b=[0,122,176];return `rgb(${Math.round(a[0]+(b[0]-a[0])*t)},${Math.round(a[1]+(b[1]-a[1])*t)},${Math.round(a[2]+(b[2]-a[2])*t)})`}
 function currentRows(ind,yr,vals){const rows=[['Provincia','Año','Indicador','Valor','Unidad','Fuente']];const names=geo?geo.features.map(f=>norm(f.properties.NOMBPROV||f.properties.NOMBPROVINCIA)).sort((a,b)=>a.localeCompare(b,'es')):Object.keys(vals).sort((a,b)=>a.localeCompare(b,'es'));names.forEach(p=>rows.push([p,+yr,ind.label,vals[p]==null?'':+vals[p],ind.unit||'',ind.source]));return rows}
 function setupDownloads(ind,yr,vals){downloads.innerHTML='<button id="mapXlsx">Descargar tabla Excel</button><button id="mapCsv">CSV</button><button id="mapPng">Descargar mapa PNG</button><button id="mapSvg">SVG</button>';const title=`Concepcion_frente_a_Junin_${ind.label}_${yr}`,rows=currentRows(ind,yr,vals);document.querySelector('#mapXlsx').onclick=()=>JP.downloadRowsXlsx(rows,title);document.querySelector('#mapCsv').onclick=()=>JP.downloadRowsCsv(rows,title);document.querySelector('#mapPng').onclick=()=>JP.downloadChartPng('juninProvinceMapSvg',title);document.querySelector('#mapSvg').onclick=()=>JP.downloadChartSvg('juninProvinceMapSvg',title)}
 function updateMeta(ind,yr,vals,nums){document.querySelector('#mapTitle').textContent=ind.label+' · '+yr;document.querySelector('#mapSource').textContent='Fuente: '+ind.source;document.querySelector('#mapLegend').innerHTML=`<span><i style="background:#EDF7FB"></i>Sin dato</span><span><i style="background:#164FA3"></i>Concepción</span>${nums.length?`<span>${fmt(ind,Math.min(...nums))} – ${fmt(ind,Math.max(...nums))}</span>`:''}`;const sv=vals['CONCEPCION'];document.querySelector('#focusValue').textContent=sv==null?'Sin dato':fmt(ind,sv);document.querySelector('#focusDetail').textContent=sv==null?`${ind.label} · ${yr}: la fuente no reporta un valor para Concepción.`:`${ind.label} en Concepción · ${yr}.`;document.querySelector('#focusRanking').textContent=nums.length?`${nums.length} provincias cuentan con dato para este indicador y año.`:''}
 function fallback(ind,yr,vals){wrap.innerHTML=`<div class="map-fallback"><div><b>No se pudo cargar la geometría del mapa.</b><span>La comparación de datos sigue disponible:</span></div><div class="map-fallback-grid">${Object.entries(vals).sort((a,b)=>a[0].localeCompare(b[0],'es')).map(([p,v])=>`<div class="map-fallback-item${p==='CONCEPCION'?' is-focus':''}"><span>${p}</span><strong>${fmt(ind,v)}</strong></div>`).join('')}</div></div>`;setupDownloads(ind,yr,vals)}
 function render(){const ind=current(),yr=String(yearSel.value),vals=ind.values[yr]||{},nums=Object.values(vals).map(Number).filter(Number.isFinite);updateMeta(ind,yr,vals,nums);if(geometrySource)geometrySource.textContent=geoLabel;if(!geo){fallback(ind,yr,vals);return}const all=geo.features.flatMap(f=>geometryPoints(f.geometry)),xs=all.map(p=>p[0]),ys=all.map(p=>p[1]),xmin=Math.min(...xs),xmax=Math.max(...xs),ymin=Math.min(...ys),ymax=Math.max(...ys),W=900,H=660,pad=24,scale=Math.min((W-2*pad)/(xmax-xmin),(H-2*pad)/(ymax-ymin)),ox=(W-(xmax-xmin)*scale)/2,oy=(H-(ymax-ymin)*scale)/2,project=([x,y])=>[ox+(x-xmin)*scale,H-(oy+(y-ymin)*scale)],min=nums.length?Math.min(...nums):0,max=nums.length?Math.max(...nums):1;let svg=`<svg id="juninProvinceMapSvg" viewBox="0 0 ${W} ${H}" class="junin-district-svg" role="img" aria-label="Mapa de provincias de Junín">`;geo.features.forEach((f,idx)=>{const p=norm(f.properties.NOMBPROV),v=vals[p],isTarget=p==='CONCEPCION',fill=isTarget?'#164FA3':colorScale(v,min,max),d=pathFor(f.geometry,project);svg+=`<path class="district-shape${isTarget?' is-focus':''}" data-idx="${idx}" d="${d}" fill="${fill}"></path>`;const pts=geometryPoints(f.geometry);if(pts.length){const xx=pts.map(a=>a[0]),yy=pts.map(a=>a[1]),c=project([(Math.min(...xx)+Math.max(...xx))/2,(Math.min(...yy)+Math.max(...yy))/2]);svg+=`<text class="province-label" x="${c[0].toFixed(1)}" y="${c[1].toFixed(1)}" text-anchor="middle">${p}</text>`}});svg+='</svg>';wrap.innerHTML=svg;setupDownloads(ind,yr,vals);wrap.querySelectorAll('.district-shape').forEach(el=>{el.addEventListener('pointermove',e=>{const f=geo.features[+el.dataset.idx],p=norm(f.properties.NOMBPROV),v=vals[p];tip.innerHTML=`<b>${p}</b>${v==null?'':`<strong>${fmt(ind,v)}</strong>`}`;tip.classList.add('show');const r=wrap.getBoundingClientRect();let x=e.clientX-r.left+14,y=e.clientY-r.top+14,tw=tip.offsetWidth||180,th=tip.offsetHeight||70;if(x+tw>r.width-8)x=e.clientX-r.left-tw-14;if(y+th>r.height-8)y=e.clientY-r.top-th-14;tip.style.left=x+'px';tip.style.top=y+'px'});el.addEventListener('pointerleave',()=>tip.classList.remove('show'))})}
 fillYears();indSel.onchange=()=>{fillYears();render()};yearSel.onchange=render;render();
 const official="https://www.idep.gob.pe/geoportal/rest/services/DATOS_GEOESPACIALES/L%C3%8DMITES/FeatureServer/4/query?where=CCDD%3D%2712%27&outFields=IDPROV%2CNOMBDEP%2CNOMBPROV%2CCCDD%2CCCPP&returnGeometry=true&outSR=4326&f=geojson";
 const urls=[{url:official,label:'Cartografía: IGN / IDEP · límites provinciales de referencia'},{url:'https://cdn.jsdelivr.net/gh/juaneladio/peru-geojson@master/peru_provincial_simple.geojson',label:'Cartografía simplificada de respaldo · límites provinciales'},{url:'https://raw.githubusercontent.com/juaneladio/peru-geojson/master/peru_provincial_simple.geojson',label:'Cartografía simplificada de respaldo · límites provinciales'}];
 async function loadGeo(){for(const src of urls){try{const r=await fetch(src.url,{cache:'force-cache'});if(!r.ok)throw new Error('HTTP '+r.status);const j=await r.json();const fs=(j.features||[]).filter(f=>{const p=f.properties||{};return norm(p.NOMBDEP||p.FIRST_NOMB)==='JUNIN'}).map(f=>{const p=f.properties||{};if(!p.NOMBPROV)p.NOMBPROV=p.NOMBPROV||p.NOMBPROVINCIA;return f});if(fs.length>=9){geo={type:'FeatureCollection',features:fs};geoLabel=src.label;render();return}}catch(e){console.warn('Mapa provincial: fuente no disponible',src.url,e)}}geoLabel='La cartografía no pudo cargarse; se muestra respaldo tabular.';render()}loadGeo();
});